name: flutter_application
description: "Приложение для погоды и расчета продолжительности дня"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# ВАШИ ЗАВИСИМОСТИ:
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  camera: ^0.11.3
  url_launcher: ^6.1.10
  intl: ^0.20.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true